### ISSUE TITLE
[회고] 2022.08.22

### ISSUE THREAD

**Issue by jihongleejihong** [lyrics4you/GNOTHI-ProjectSocrates#2]
사실:
데이터톤의 한주가 시작되었다.
느낌:
생각보다 시간이 없는데, 머릿속에 분명한 것은 없는 느낌이다.
교훈:
일단 앉아 있는 시간을 늘려봐야겠다.

**Comment by ElleryVernon** [comment]
사실: 여기저기 다른 팀 관광을 다녔습니다.

느낌: 다들 뭔가 고민이 많으면서 동시에 즐거워 보였습니다.

교훈: 그만 놀러 다니고 열심히 해야할 것 같습니다.

**Comment by freejin23** [comment]
사실: 
전체적인 프로젝트 방향을 설정하고 네이버 블로그 크롤링으로 고군분투했습니다.
느낌:
네이버의 크롤링은 지난 프로젝트들과는 다르게 어려웠습니다.
교훈:
하지만 천우신조. 열심히 하다보면 또 길이 보입니다. 빠이팅!

**Comment by jxxxxharu** [comment]
사실:
블로그 글 키워드 뽑기

느낌:
키워드 뽑는 방법엔 또 뭐가 있을까?

교훈:
이제 크롤링도 마무리됐으니, 서비스 구체화 필요할 듯

**Comment by jaeunyun** [comment]
사실: 게더타운을 이용해서 데이터톤을 시작하게 되었습니다.
느낌: 정신이 딴 데 팔려버려서 아찔합니다.
교훈: 천우신조.. 간절히 원하면..
