### ISSUE TITLE
[회고] 2022.08.24

### ISSUE THREAD

**Issue by freejin23** [lyrics4you/GNOTHI-ProjectSocrates#6]
오늘의 회고를 자유롭게 적어주세요~!

**Comment by jihongleejihong** [comment]
사실:
감정 metric을 만드느라 거의 하루종일 보냈다.
느낌:
수학은 재밌기도 하지만 늘 어려운 존재...
교훈:
수학 공부를 좀 더 해놨으면 빨리 끝났겠지.... 공부 공부....

**Comment by jxxxxharu** [comment]
사실: 키워드 추출 baseline이 나왔다
느낌: 오늘따라 뭐 자꾸 막힐 때마다 집중이 깨졌는데, 팀원들이 으쌰으쌰 해주셔서 이어나갈 수 있었다. 감삼당😚
교훈: 마지막까지 좀만더 힘내서 머리를 굴려보자 나 자신아
